options:
  install_sources:
    default: |
      - "https://deb.nodesource.com/node_6.x main"
  install_keys:
    default: |
      - '68576280'
  port:
    type: int
    default: 3000
    description: |
      "Port for BurrowUI"

